server:
  port: 8761 # Default port for Eureka Server

eureka:
  client:
    register-with-eureka: false # Eureka Server does not register itself
    fetch-registry: false # Eureka Server does not fetch the registry